test_format = 1.0

[default]

    [default.curl_tests]
    home.path = "/"
    home.logged_on_sso = true
    home.expect_title = "WireGuard Clients"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.15d9c1a09457fb9d71fd0519cd16a0492669a8a9.name = "Upgrade from 0.4.0~ynh1"
    test_upgrade_from.15d9c1a09457fb9d71fd0519cd16a0492669a8a9.args.admin = "package_checker"
    test_upgrade_from.15d9c1a09457fb9d71fd0519cd16a0492669a8a9.args.domain = "sub.domain.tld"
